goog.provide('instruisto.correlative');
goog.require('cljs.core');
goog.require('instruisto.effects');
goog.require('domina.events');
goog.require('domina');
goog.require('goog.net.XhrIo');
instruisto.correlative.init_correlative_toggle = (function init_correlative_toggle(elem){
return domina.events.listen_BANG_.call(null,elem,"\uFDD0'click",(function (event){
var display__6547 = [cljs.core.str(domina.text.call(null,elem))].join('');
var hidden__6548 = [cljs.core.str(domina.attr.call(null,elem,"headers"))].join('');
instruisto.effects.fade_out_elem.call(null,elem,500);
domina.set_text_BANG_.call(null,elem,[cljs.core.str(hidden__6548)].join(''));
domina.set_attr_BANG_.call(null,elem,"headers",[cljs.core.str(display__6547)].join(''));
return instruisto.effects.fade_in_elem.call(null,elem,500);
}));
});
instruisto.correlative.start_correlative = (function start_correlative(){
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kio"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tio"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-io"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxio"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-nenio"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kiu"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tiu"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-iu"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxiu"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-neniu"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kia"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tia"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-ia"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxia"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-nenia"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kiel"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tiel"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-iel"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxiel"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-neniel"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kie"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tie"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-ie"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxie"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-nenie"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kiam"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tiam"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-iam"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxiam"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-neniam"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kiom"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tiom"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-iom"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxiom"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-neniom"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kial"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-tial"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-ial"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxial"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-nenial"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-kies"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-ties"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-ies"));
instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-cxies"));
return instruisto.correlative.init_correlative_toggle.call(null,domina.by_id.call(null,"correlative-nenies"));
});
